<?php

namespace Craftgate\Model;

class BnplCartItemType
{
    const MOBILE_PHONE_PRICE_ABOVE_REGULATION_LIMIT = 'MOBILE_PHONE_PRICE_ABOVE_REGULATION_LIMIT';
    const MOBILE_PHONE_PRICE_BELOW_REGULATION_LIMIT = 'MOBILE_PHONE_PRICE_BELOW_REGULATION_LIMIT';
    const TABLET = 'TABLET';
    const COMPUTER = 'COMPUTER';
    const CONSTRUCTION_MARKET = 'CONSTRUCTION_MARKET';
    const GOLD = 'GOLD';
    const DIGITAL_PRODUCTS = 'DIGITAL_PRODUCTS';
    const SUPERMARKET = 'SUPERMARKET';
    const WHITE_GOODS = 'WHITE_GOODS';
    const WEARABLE_TECHNOLOGY = 'WEARABLE_TECHNOLOGY';
    const SMALL_HOME_APPLIANCES = 'SMALL_HOME_APPLIANCES';
    const TV = 'TV';
    const GAMES_CONSOLES = 'GAMES_CONSOLES';
    const AIR_CONDITIONER_AND_HEATER = 'AIR_CONDITIONER_AND_HEATER';
    const ELECTRONICS = 'ELECTRONICS';
    const MOM_AND_BABY_AND_KIDS = 'MOM_AND_BABY_AND_KIDS';
    const SHOES = 'SHOES';
    const CLOTHING = 'CLOTHING';
    const COSMETICS_AND_PERSONAL_CARE = 'COSMETICS_AND_PERSONAL_CARE';
    const FURNITURE = 'FURNITURE';
    const HOME_LIVING = 'HOME_LIVING';
    const AUTOMOBILE_MOTORCYCLE = 'AUTOMOBILE_MOTORCYCLE';
    const OTHER = 'OTHER';
}