<?php

namespace Craftgate\Model;

class LoyaltyType
{
    const REWARD_MONEY = 'REWARD_MONEY';
    const ADDITIONAL_INSTALLMENT = 'ADDITIONAL_INSTALLMENT';
    const POSTPONING_INSTALLMENT = 'POSTPONING_INSTALLMENT';
    const EXTRA_POINTS = 'EXTRA_POINTS';
    const GAINING_MINUTES = 'GAINING_MINUTES';
    const POSTPONING_STATEMENT = 'POSTPONING_STATEMENT';
}
