name: autoupdate

on:
  push:
    branches:
      - master

jobs:
  autoupdate:
    name: autoupdate
    runs-on: ubuntu-22.04
    steps:
      - uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          DRY_RUN: "false"
          PR_FILTER: "auto_merge"
          PR_LABELS: "auto-update,keep up-to-date"
          PR_READY_STATE: "ready_for_review"
          MERGE_MSG: "Branch was auto-updated."
          RETRY_COUNT: "2"
          RETRY_SLEEP: "60000"
          MERGE_CONFLICT_ACTION: "fail"