name: Build TokenPay PHP Client

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - 'samples/**'
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - 'samples/**'

jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['5.3', '5.4', '5.5', '5.6', '7.0', '7.1', '7.2', '7.3', '7.4']
    name: Build with PHP ${{ matrix.php-versions }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: xdebug
          extensions: intl
          ini-values: "post_max_size=256M"
      - name: Check PHP Version
        run: |
          php -v
          php -r "if(strpos(phpversion(), '${{ matrix.php-versions }}') === false) {throw new Exception('Wrong PHP version Installed');}"
      - name: Testing Composer version
        run: |
          composer -V
          php -r "if(strpos(@exec('composer -V'), 'Composer version') === false) {throw new Exception('Composer not found');}"
      - name: Run Unit Tests
        run: |
          composer install
          composer test
